# This is an example daemon_settings.yml file.
# See https://lbry.tech/resources/daemon-settings for all configuration keys and values

share_usage_data: True

lbryum_servers:
  - lbryumx1.lbry.com:50001
  - lbryumx2.lbry.com:50001
  - lbryumx4.lbry.com:50001

blockchain_name: lbrycrd_main

data_dir: /home/lbry/.lbrynet
download_directory: /home/lbry/downloads

save_blobs: true
save_files: false
dht_node_port: 4444
peer_port: 3333
use_upnp: true

# Concurrency caps (tune for your environment)
# stream_load_concurrency: 24        # max streams initialized in parallel during startup
# stream_save_concurrency: 8         # max concurrent save_file resumes after startup
# claim_callback_concurrency: 24     # max concurrent claim-update callbacks

#components_to_skip:
#  - hash_announcer
#  - blob_server
#  - dht
#  - libtorrent_component   # torrent support is optional/incomplete; skip by default

# Wallet server (hub) behavior
# hub_timeout: 30                  # seconds to wait for a hub request
# concurrent_hub_requests: 32      # max concurrent JSON-RPC calls to hub
# cycle_hubs_on_not_found: true    # try other hubs if resolve returns NOT_FOUND
# cycle_hubs_on_blocked: false     # also cycle hubs if resolve returns BLOCKED
# max_hub_cycles: 3                # limit number of alternate hubs to try (0 = no limit)
