FROM python:3.13-bookworm@sha256:073ffebb96ae4d0ed73ccad59f08c47bd84af8a79f5258130f8458ac50ad9ff4

RUN apt-get update && apt-get install -y --no-install-recommends ffmpeg \
    && rm -rf /var/lib/apt/lists/*
COPY docker/test-constraints.txt docker/build-requirements.txt /opt/
RUN python -m pip install --no-cache-dir -c /opt/test-constraints.txt \
    pip setuptools wheel Cython

WORKDIR /opt/lbry-sdk
COPY setup.py setup.cfg README.md ./
COPY lbry ./lbry
RUN python -m pip install --no-cache-dir --no-build-isolation \
    -c /opt/test-constraints.txt -r /opt/build-requirements.txt -e '.[test,hub,lint]' \
    && python -m pip check
RUN orchstr8 download && echo \
    '8d85a3bade3e7c54596b1e4298101b23eb3788fda617b17a2bfd3d067a3f4017  lbry/wallet/bin/lbcd_0.22.100-rc.0_linux_amd64.tar.gz' \
    | sha256sum -c - && echo \
    '970c9595227cd596ef3c6d9eafa350e2427aea9aea9f73f1aa733226389122ee  lbry/wallet/bin/lbcwallet_0.13.100-alpha.0_linux_amd64.tar.gz' \
    | sha256sum -c -
COPY tests ./tests
RUN python -m tests.integration.claims.fixtures
RUN python -m pip freeze > /opt/baseline-packages.txt \
    && useradd --create-home --uid 1000 sdk \
    && chown -R sdk:sdk /opt/lbry-sdk
USER sdk
ENV PYTHONUNBUFFERED=1
CMD ["python", "-m", "unittest", "discover", "-v", "tests.unit"]
