services:
    websdk:
        build:
            context: ..
            dockerfile: docker/Dockerfile.web
        ports:
            - '127.0.0.1:5279:5279'
            - '127.0.0.1:5280:5280'
        volumes:
            - ./webconf.yaml:/webconf.yaml:ro
